Fix QA error in nativesdk-dtc
libfdt library has a different naming scheme which is causing
below QA error.

ERROR: nativesdk-dtc-1.4.4-r0 do_package_qa: QA Issue: -dev
package contains non-symlink .so: nativesdk-dtc-dev path
'/work/x86_64-nativesdk-oesdk-linux/nativesdk-dtc/1.4.4-r0/
 packages-split/nativesdk-dtc-dev/usr/local/oecore-x86_64/
sysroots/x86_64-oesdk-linux/usr/lib/libfdt-1.4.4.so'
[dev-elf]

Fix this by adjusting FILES packaging rules.

Change-Id: I2b4360ac3b1ebd4ae11d019f640d43896d0a1f36