Revert "meta-qti-bsp: Add sdk on qti-multimedia"
 Need this revert to address following error on 6.2.4 branch

 ```
 ERROR: When reparsing
 poky/meta/recipes-core/meta/meta-environment.bb:do_generate_content,
 the basehash value changed from
 8799bfe1dca41f7f133da9cfb2db9053cb580fa49992c312f6a3329f521d5c29 to
 8e73e1cbd4ab731dd35ff91642c98c703f16d39c3baed32c0df9d28ce3cb4f0f.
 The metadata is not deterministic and this needs to be fixed.
 ERROR: The following commands may help:
 ERROR: $ bitbake meta-environment-qcs610-odk-64 -cdo_generate_content -Snone
 ERROR: Then:
 ERROR: $ bitbake meta-environment-qcs610-odk-64 -cdo_generate_content -Sprintdiff

 ```

This reverts commit 2898021c14c973b0c68e3f7e565430a830502381.

Change-Id: Ieccbe701b24eed323489fc150a946bcc1ed4a7bd